train:
  _target_: src.datasets.LibrispeechDataset
  part: "train-clean-100"
  max_audio_length: 20.0
  max_text_length: 200
  instance_transforms: ${transforms.instance_transforms.train}
# we filter partitions in one batch test to check the pipeline
# do not filter test dataset, you want to evaluate on the whole dataset
val:
  _target_: src.datasets.LibrispeechDataset
  part: "test-clean"
  max_audio_length: 20.0
  max_text_length: 200
  instance_transforms: ${transforms.instance_transforms.inference}
