defaults:
  - model: deepspeech2
  - metrics: inference
  - datasets: inference # inference_custom
  - dataloader: example
  - transforms: inference
  - _self_
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
  use_bpe: True
  alphabet_path: "data/other/tokenizer-wiki.json"
  test_without_lm: True
inferencer:
  device_tensors: [ "spectrogram", "text_encoded" ] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "predict" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "data/other/model_best.pth" # path to the pretrained model
